### ISSUE TITLE
Mediensuche funktioniert nicht

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#10]
Da passt das mit dem Konstruktor wohl doch nicht:

`Fatal error: Uncaught Error: Call to undefined method BiblioSearchQuery::Query() in /var/www/web14/html/openbiblio/classes/BiblioSearchQuery.php:30 Stack trace: #0 /var/www/web14/html/openbiblio/shared/biblio_search.php(127): BiblioSearchQuery->__construct() #1 {main} thrown in /var/www/web14/html/openbiblio/classes/BiblioSearchQuery.php on line 30`

**Comment by kroerig** [comment]
Das Problem dürfte folgendes sein:

`class BiblioSearchQuery extends Query {
  function __construct() {
    $this->Query();
    $this->_loc = new Localize(OBIB_LOCALE,"classes");
  }
(...)
}
`

`$this->Query()` wäre jetzt aber `__construct()` aus der Klasse _query_

**Comment by kroerig** [comment]
Ah, gefunden.

man ersetze `$this->Query()` durch `parent::__construct();`

**Comment by ThomasChr** [comment]
Yes 👍

**Comment by kroerig** [comment]
Und auch das komme wieder in Rudeln vor.

**Comment by ThomasChr** [comment]
Schätze das wird man auch nicht automatisch fixen können.
Aber wir kommen doch gut vorran, ich bin jedenfalls zufrieden bislang!

**Comment by kroerig** [comment]
Ja, wenn man einmal einen Einstieg gefunden hat.

**Comment by kroerig** [comment]
So, das Problem mit den Klassen habe ich beseitig. Jetzt schlägt er hier auf:

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /var/www/web14/html/openbiblio/classes/BiblioQuery.php:129 Stack trace: #0 /var/www/web14/html/openbiblio/shared/biblio_view.php(101): BiblioQuery->doQuery('251', 'opac') #1 {main} thrown in /var/www/web14/html/openbiblio/classes/BiblioQuery.php on line 129`

**Comment by ThomasChr** [comment]
Ich denke da muss ein strlen() statt count() hin.
Der will wohl die Anzahl der Buchstaben in einem String zählen.
