### ISSUE TITLE
Neue Mitglieder anlegen funktioniert nicht

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#13]
`Fatal error: Uncaught mysqli_sql_exception: Incorrect date value: '0000-00-00' for column 'mbrshipend' at row 1 in /var/www/web14/html/openbiblio/classes/QueryMysqli.php:78 Stack trace: #0 /var/www/web14/html/openbiblio/classes/QueryMysqli.php(78): mysqli_query(Object(mysqli), 'insert into mem...') #1 /var/www/web14/html/openbiblio/classes/Query.php(76): QueryMysqli->query('insert into mem...') #2 /var/www/web14/html/openbiblio/classes/Query.php(253): Query->_act('insert into mem...') #3 /var/www/web14/html/openbiblio/classes/Query.php(258): Query->_exec('insert into mem...') #4 /var/www/web14/html/openbiblio/classes/MemberQuery.php(219): Query->exec('insert into mem...') #5 /var/www/web14/html/openbiblio/circ/mbr_new.php(90): MemberQuery->insert(Object(Member)) #6 {main} thrown in /var/www/web14/html/openbiblio/classes/QueryMysqli.php on line 78`

**Comment by kroerig** [comment]
den Fall hatte ich schon mal bei einer anderen Software. Das liegt an MySQL/Maria DB.

Lässt sich mit einem `"SET @@SQL_MODE = REPLACE(@@SQL_MODE, 'NO_ZERO_DATE', '')"` beheben. Nur wohin damit im Quellcode?

**Comment by ThomasChr** [comment]
Theoretisch könntest du das wohl direkt nach dem mysqli_connect() in der QueryMysql.php machen. Ich würde zumindest so grundsätzliche Datenbankkonfigurationen direkt nach dem connect vermuten.

**Comment by kroerig** [comment]
habs unter bekommen. Keine Fehlermeldung mehr beim Anlegen. Aber beim Bearbeiten kommt noch was.

```
Warning: Undefined array key "pageErrors" in /var/www/web14/html/openbiblio/circ/mbr_view.php on line 83
Warning: Trying to access array offset on value of type null in /var/www/web14/html/openbiblio/circ/mbr_view.php on line 84
```

im Quelltext:

```
  #****************************************************************************
  #*  Prüfung auf Hinweis wegen Ablauf der Mitgliedschaft vor Rückgabedatum
  #*  Derzeit abgedeckt durch Missbrauch des Fehlercodes und Markierung mit !!! davor
  #****************************************************************************
  $dueMsg = "";
  $pgErrors = $_SESSION['pageErrors'];
  if (substr($pgErrors["barcodeNmbr"], 0, 3) === '!!!') {
          $dueMsg = "<font class=\"error\">".substr($pgErrors["barcodeNmbr"], 3)."</font><br><br>";
          unset($postVars);
          unset($pageErrors);
  }

```

Ich habe aber noch nicht aus, wann und wo diese SESSION-Variable gesetzt wird, oder eben nicht.

**Comment by ThomasChr** [comment]
Afaik hat php früher bei Zugriff auf einen nicht vorhandenen Array Key einfach leer zurückgegeben. So "nett" ist es jetzt nicht mehr. Du musst also prüfen ob es den Array Key überhaupt gibt (array_key_exists()). Gibt es ihn nicht dann könntest du ihn einfach leer anlegen oder einfach die ganze Logik hier garnicht erst ausführen, weil wenn es den Eintrag im Array garnicht gibt dann kann er 100% auch nicht mit '!!!' anfangen.

Das ist manchmal etwas kniffelig damit man da die Logik nicht kaputt macht, deshalb möglichst davor und danach testen.

**Comment by kroerig** [comment]
umschlossen mit einem `if array_key_exists()`, sieht es gut aus.

**Comment by ThomasChr** [comment]
👍
