### ISSUE TITLE
Reports - create_function loswerden

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#14]
Die Reports nutzen `create_function()`

Diese Funktion ist  seit PHP 7.2 veraltet und mit 8.0 komplett weggefallen. Da muss also eine neue Logik her.

`Fatal error: Uncaught Error: Call to undefined function create_function() in /var/www/web14/html/openbiblio/classes/Report.php:119 Stack trace: #0 /var/www/web14/html/openbiblio/classes/Report.php(262): Report->columnNames() #1 /var/www/web14/html/openbiblio/reports/run_report.php(174): Report->pageTable(1, Object(Table)) #2 {main} thrown in /var/www/web14/html/openbiblio/classes/Report.php on line 119`

**Comment by ThomasChr** [comment]
https://stackoverflow.com/questions/48161526/php-7-2-function-create-function-is-deprecated

**Comment by kroerig** [comment]
verstehe ich das richtig, dass dann aus

`create_function('$x', 'return $x["name"];')`

```
function($x) use ($x["name"]) {
    return $x["name"];
}

```
wird?

**Comment by ThomasChr** [comment]
Ich denke das use() kannste komplett weglassen, das bräuchtest du nur wenn du eine Variable die dort ist wo die Funktion erzeugt wird mit reinnehmen willst (scope), aber das brauchst hier ned.
An der Stelle wird dem array_map() ja nur eine Funktion gegeben die er für jeden Wert des Arrays ausführen soll.
Alternativ kannst du die Funktion auch ganz normal woanders schreiben und nur den Namen reingeben. Dann ist sie halt nicht mehr anonym und exakt dort erzeugt wo du sie brauchst. Ist Geschmackssache, die PHP Anleitung macht es z.B. nicht anonym: https://www.php.net/manual/en/function.array-map.php
