### ISSUE TITLE
Ausleihe funktioniert nicht

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#15]
`Fatal error: Uncaught Error: Undefined constant "OBIB_LOCK_NAME" in /var/www/web14/html/openbiblio/classes/Query.php:107 Stack trace: #0 /var/www/web14/html/openbiblio/classes/CircQuery.php(26): Query->lock() #1 /var/www/web14/html/openbiblio/circ/checkout.php(54): CircQuery->checkout_e('10', '011781') #2 {main} thrown in /var/www/web14/html/openbiblio/classes/Query.php on line 107`

**Comment by ThomasChr** [comment]
Ja, nee, ist halt ned definiert :-)
Muss mal mit der IDE in Ruhe schauen wo das eigentlich definiert wird. Wenn dus nicht bis dahin eh gefunden hast!

**Comment by kroerig** [comment]
kommt nur in der classes/Query.php vor.

**Comment by kroerig** [comment]
Da gibt es zwei Werte: OBIB_LOCK_NAME und OBIB_LOCK_TIMEOUT, die als Parameter übergeben werden, aber nirgends definiert.

**Comment by ThomasChr** [comment]
Wenn die beiden Konstanten wirklich nicht definiert werden dann würd ich sie mit einem Wunschstring ("bibliolock") und den timeout mit 0 setzen. Das sollte wahrscheinlich dem entsprechen was man hier erreichen wollte, siehe: https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock

**Comment by kroerig** [comment]
Zumindest wirft es so keinen Fehler. Und ich sehe auch nicht, dass irgendwas nicht funktioniert.

**Comment by ThomasChr** [comment]
Sehr schön :-)
