### ISSUE TITLE
Berichte: PDF erzeugen schlägt fehl

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#22]
```
Warning: Undefined array key "x-base" in /var/www/web14/html/openbiblio/classes/Lay.php on line 319
Warning: Undefined array key "y-base" in /var/www/web14/html/openbiblio/classes/Lay.php on line 319
```
aber die Werte finde ich da nicht. Wo kommen die her?

**Comment by ThomasChr** [comment]
Die kommen aus $d welches aus dem Array (Parameter) $dim kommt.
Ich denke ein array_key_exists mit $d als key sollte das schon richten…

**Comment by kroerig** [comment]
Hm. Ne,  der braucht die Werte.

**Comment by ThomasChr** [comment]
Die scheinen aber ja ned drin zu sein? Hmmm, ich gucks mir mal am Montag im Debugger an. Wie kann ichs nachstellen?

**Comment by kroerig** [comment]
Unter Berichte, die Inventurliste aufrufen, und auf "Liste drucken"

Die Werte sind da, aber nicht als zweidimensionales Arry, wie die Schleife es erwartet.

**Comment by kroerig** [comment]
print_r ($dim):

`Array
(
    [x] => 75.996
    [y] => 20.754
    [x-base] => 3.024
    [y-base] => 16.83
)
<br />
<b>Warning</b>:  Undefined array key "x-base" in <b>/var/www/web14/html/openbiblio/classes/Lay.php</b> on line <b>320</b><br />
<br />
<b>Warning</b>:  Undefined array key "y-base" in <b>/var/www/web14/html/openbiblio/classes/Lay.php</b> on line <b>320</b><br />`

**Comment by ThomasChr** [comment]
Tja, dann müsste es EIGENTLICH gehen.
Nach meiner Recherche ist auch quasi jeder String als Array Key erlaubt, das Minus/Bindestrich sollte EIGENTLICH auch nicht stören.
Ich probier später mal ein bisschen rum.

Können wir den "x-base" in z.B. "xBase" umbenennen? Sind wir sicher dass es nicht ein anderer Bindestrich als beim erzeugen ist (in Unicode gibts ne ganze Latte gleich aussehender Bindestriche). Ist evtl. ein nicht druckbares Sonderzeichen reingerutscht?

**Comment by ThomasChr** [comment]
"x-base" fehlt in $this->child_max_dim:

![image](https://user-images.githubusercontent.com/13014163/188308763-e6a96cdc-35bd-46e1-89f9-31672cfd67cc.png)

**Comment by ThomasChr** [comment]
Hier ist noch was mit komischem Umlaut, oder hast das evtl. schon gefixt?
Nutze aktuellen master...
![image](https://user-images.githubusercontent.com/13014163/188309344-fd717916-07b9-4f36-aea2-027f46a83c7e.png)

Den Fehler mit dem Array Zugriff hab ich gefixt, weiterhin kommt noch ein gemeinerer. Bin da grad dran.

**Comment by ThomasChr** [comment]
Hier auch bei Nächste...
![image](https://user-images.githubusercontent.com/13014163/188309420-d03d1b2d-95b5-43ef-822d-fec8d2bb9477.png)

**Comment by ThomasChr** [comment]
PR ist fertig. Bei mir kam eine PDF raus. Prüf bitte noch ob das auch mit Bildern klappt - da musste ich etwas mehr anpssen.
Wenn du Fragen hast, nur her damit, ich denke ich weiß was ich getan habe :-)

**Comment by kroerig** [comment]
> Hier ist noch was mit komischem Umlaut, oder hast das evtl. schon gefixt? Nutze aktuellen master... ![image](https://user-images.githubusercontent.com/13014163/188309344-fd717916-07b9-4f36-aea2-027f46a83c7e.png)
> 
> Den Fehler mit dem Array Zugriff hab ich gefixt, weiterhin kommt noch ein gemeinerer. Bin da grad dran.

Bei mir stimmen die Umlaute da.

**Comment by kroerig** [comment]
Hab aber gerade noch ein paar Stellen gefunden und korrigiert.
