### ISSUE TITLE
Login ohne Anmeldedaten

### ISSUE THREAD

**Issue by kroerig** [kroerig/openbiblio-german#29]
`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /var/www/web14/html/openbiblio/shared/login.php:29 Stack trace: #0 {main} thrown in /var/www/web14/html/openbiblio/shared/login.php on line 29`

**Comment by ThomasChr** [comment]
Jo, den hatte ich auch nach importieren der Demodaten bemerkt, die beinhalten keine User, oder?
War aber zu faul den auch gleich zu beheben.

**Comment by kroerig** [comment]
nein, der Dump hat keinen Inhalt für die Staff-Tabelle. Den legt legt ja das Install-Script an.

**Comment by ThomasChr** [comment]
pageErrors ist ein String, wird aber wie ein Array zugegriffen, das kann so ned klappen. pageErrors als Array definieren und dann checken ob er auch richtig angezeigt wird

**Comment by kroerig** [comment]
sieht gut aus.
